apiVersion: batch/v1
kind: Job
metadata:
  # Prefix name of job with user and timestamp
  name: kishwar-marginpolish
spec:
  backoffLimit: 0
  # Delete the log after a minute
  ttlSecondsAfterFinished: 6000
  template:
    spec:
      containers:
      - name: marginpolish
        image: tpesout/margin_polish:latest
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        - |
          set -e
          # DEBIAN_FRONTEND=noninteractive apt-get update -qq -y && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y awscli
          # echo "nameserver 1.1.1.1" > /etc/resolv.conf

          # DOWNLOAD FILES
          aws s3 cp s3://lc2019/guppy_3.0.5_bacterial/train_test/data/Bacterial.reads_to_shasta.validate_StaphAur.bam .
          aws s3 cp s3://lc2019/guppy_3.0.5_bacterial/train_test/data/Bacterial.reads_to_shasta.validate_StaphAur.bam.bai .
          wget https://storage.googleapis.com/kishwar-helen/bacterial_data/guppy_305/validation_data/Bacterial_shasta_assembly_validate_StaphAur.fasta

          mkdir mp_output

          # RUN MARGINPOLISH
          time /opt/MarginPolish/build/marginPolish \
          Bacterial.reads_to_shasta.validate_StaphAur.bam \
          Bacterial_shasta_assembly_validate_StaphAur.fasta \
          /opt/MarginPolish/params/allParams.np.human.r94-g305.json \
          -o ./mp_output/staph_aur_mp \
          -t 72 \
          -f

          # UPLOAD OUTPUTS
          timestamp=$(date +%Y_%m_%d_%H_%M_%S)
          aws s3 cp --recursive mp_output s3://kishwar-k8s/marginpolish_outputs/mp_$timestamp/
        volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
        - mountPath: /root/.aws
          name: s3-credentials
          readOnly: true
        resources:
          requests:
            cpu: "72"
            memory: "256G"
            ephemeral-storage: "512G"
          limits:
            cpu: "72"
            memory: "256G"
            ephemeral-storage: "512G"
        # command: ["/bin/bash", "-c"]
        # args: ['for i in {1..10}; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']

        # command: ["python3", "/opt/helen/call_consensus.py"]
        # args: ["-h"]
      restartPolicy: Never
      volumes:
      - name: scratch-volume
        emptyDir: {}
      - name: s3-credentials
        secret:
          secretName: kube-s3-credentials
